"""create tables

Revision ID: 3f4d025d0922
Revises: 
Create Date: 2025-10-25 08:58:57.455554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4d025d0922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commissions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('import_method', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_tags',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('trade_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_tags')
    op.drop_table('trades')
    op.drop_table('tags')
    # ### end Alembic commands ###